### ISSUE TITLE
Make it available from MathProgBase

### ISSUE THREAD

**Issue by blegat** [jump-dev/CSDP.jl#1]
Do you have any plan on making it available from MathProgBase ?
We might want to implement the `AbstractSDPModel` (see [here](https://github.com/daviddelaat/SemidefiniteProgramming.jl/issues/1)) and then make it available through the `SDPtoConicBridge`. Does that match your plan ?

**Comment by EQt** [comment]
Would be cool. Unfortunately, I don't know when I will have time to do it. I am uncertain, whether it is still working at the moment. Started this wrapper for a different project, some time ago. Contributions are welcome
