### ISSUE TITLE
Register it

### ISSUE THREAD

**Issue by blegat** [jump-dev/CSDP.jl#12]
@EQt Don't you think that this package is ready to be registered ?

**Comment by EQt** [comment]
Yes. Why not register it. Do you want to do it (I have no experience in doing it).

**Comment by blegat** [comment]
I have opened the PR https://github.com/JuliaLang/METADATA.jl/pull/7222 :)

**Comment by blegat** [comment]
@EQt Could you update the github url of https://ci.appveyor.com/project/EQt/csdp-jl it does not detect new pushes since we moved CSDP to JuliaOpt

**Comment by blegat** [comment]
@EQt CSDP is now registered, can you update appveyor with the JuliaOpt address ?

**Comment by mlubin** [comment]
@blegat, I'd just enable appveyor on your own at this point.

**Comment by blegat** [comment]
@mlubin done :)
