### ISSUE TITLE
Being able to modify the parameters

### ISSUE THREAD

**Issue by blegat** [jump-dev/CSDP.jl#15]
`easy_sdp` get its parameters from `param.csdp` and if it does not find this file, it gives the default values. Currently we need to ask the user to write this `param.csdp` file himself. It would be nice to write this file automatically or, even better, to build the parameter structure ourself and not rely on `easy_sdp` and call `sdp` directly.

**Comment by blegat** [comment]
An example of `param.csdp` file that removes verbosity while leaving the other parameters at their default value can be found [here](https://github.com/JuliaOpt/CSDP.jl/blob/master/test/param.csdp).

**Comment by mlubin** [comment]
CSDP should throw an error if you provide parameters in the constructor instead of silently ignoring them.

**Comment by blegat** [comment]
I am working on implementing the support for the parameters, I will add the error for the unknown options at the same time :)

**Comment by blegat** [comment]
Once can now do `CSDPSolver(printlevel=0)` to make it silent :)
