### ISSUE TITLE
Segmentation fault from the example

### ISSUE THREAD

**Issue by blegat** [jump-dev/CSDP.jl#2]
I get a segmentation fault (as Travis does) when I run the example on Julia 0.5.1-pre+2 Ubuntu 16.04 and Csdp-6.1.1.
It is happening at `makefill.c:74` which is basically doing

```
for (i=1; i<=k; i++) {
    ptr=constraints[i].blocks;
    while (ptr != NULL) {
        for (j=1; j<=ptr->numentries; j++) {
            p=ptr->iindices[j];
            q=ptr->jindices[j]; # It fails here
        }
        ptr=ptr->next;
    }
}
```

I think the issue is that `iindices` and `jindices` are julia arrays and you gave the pointers to `Csdp` pretending it is `C` arrays. However if `iindices` or `jindices` gets removed by the garbage collector then when `Csdp` tries to access it then it gets a segmentation fault.

@joehuchette @mlubin Are you giving the pointer of a Julia Vector to the C library in any of your solver wrappers or is this something that should be avoided for the above reason ?

**Comment by mlubin** [comment]
If Csdp holds onto the Julia vector pointer instead of making a copy, then the fix is to keep a reference to the Julia vector on the Julia side (e.g., in the model object) to keep the GC happy.
