### ISSUE TITLE
Solver does not use options passed by user

### ISSUE THREAD

**Issue by jomi2801** [jump-dev/CSDP.jl#20]
If I run `CSDP` using `printlevel=1` and `printlevel=0`, the same output is generated, i.e. 
the user's `printlevel` is not used by the solver. This holds for all options except `verbose`. Here some code to reproduce the issue
```
using CSDP

include(joinpath(Pkg.dir("MathProgBase"),"test","conicinterface.jl"))

println("printlevel=1 (default)")
coniclineartest(CSDP.CSDPSolver(), duals=true, tol=1e-6)

println("printlevel=0")
coniclineartest(CSDP.CSDPSolver(printlevel=0), duals=true, tol=1e-6)
```
Moreover, the function `checkoptions` is never called since it does not return an error if we try to set the option `no_option` which is not a valid option for CSDP. Here some code 
```
coniclineartest(CSDP.CSDPSolver(no_option=false), duals=true, tol=1e-6)

```
However, it turns out that if I use a `param.csdp` file, I can pass options to CSDP. 

Why does the issue occur? I think I pass options properly since I follow the `README` file. Moreover, the interface should allow passing options through the constructor as explained in the file. 

I would very much appreciate your help!

**Comment by jomi2801** [comment]
The issue is related to  #15 which is about providing functionality for options.

**Comment by blegat** [comment]
Are you using the latest development with MathOptInterface version or v0.0.3 with MathProgBase ?
The support for options has only been added for the latest development version with MathOptInterface. For MathProgBase, you should use the `param.csdp` file and v0.0.3.

**Comment by jomi2801** [comment]
I was using MathProgBase and version 0.0.3 in the first place. The latest development using MathOptInterface works as expected. Thank you very much for help!

**Comment by blegat** [comment]
I have readded the MathProgBase interface on master, and it now also supports options so if you use master you should be able to use MathProgBase with options
