### ISSUE TITLE
Windows support

### ISSUE THREAD

**Issue by blegat** [jump-dev/CSDP.jl#5]
@EQt where are we on Windows support ? Appveyor is still failing :'(

**Comment by EQt** [comment]
I don't know why it is failing. Will try to investigate next time I have access to a windows machine. The Appveyor console output is not that helpful for that...

**Comment by EQt** [comment]
I am uncertain whether the `Ref` construct in `initsoln` may cause some memory leaks. Inveoking `writeprob` fails on my Windows machine (Windows 8, Julia v0.5.0). Do you, @blegat, see any possibilities to debug that or even better test it on Linux?
As soon as I will have time I will give [`valgrind`](http://docs.julialang.org/en/release-0.5/devdocs/valgrind/) a try.

**Comment by blegat** [comment]
[Here](http://docs.julialang.org/en/release-0.5/manual/calling-c-and-fortran-code/) it is said that `Ref` should be used for giving pointers to Julia variables, which is what we need to do in `initsoln`.
One last thing that we are not doing properly is that we do `type sparseblock` instead of `immutable sparseblock`. This makes `function ConstraintMatrix(csdp::constraintmatrix, k::Integer)` fails.
We need to make `sparseblock` immutable but for that we need to update the function `function setindex!(A::SparseBlock, v, i, j)`. This may be what is causing errors on Windows.

**Comment by EQt** [comment]
Thanks for the reference. There might be several issues on Windows: on my virtual machine (64 bit), I get a different error than AppVeyor which is probably due to `libopenblas`. I will investigate that further as soon as I have time (could be next week).

Regarding this `immutable` issue: have you thought about `pointer_from_objref`?

**Comment by blegat** [comment]
What do you mean with `pointer_from_objref` ?

**Comment by blegat** [comment]
On Windows 7 64 bits with Julia v0.5, I get:

``` julia
julia> Pkg.test("CSDP")
INFO: Testing CSDP
Test Summary:      | Pass  Total
  Interact with BLAS |    1      1
Test Summary:      | Pass  Total
  Call libcsdp.norm1 |    1      1
Iter:  0 Ap: 0.00e+000 Pobj:  3.0700992e+002 Ad: 0.00e+000 Dobj:  0.0000000e+000
```

And then it stays at `Iter 0`...

**Comment by blegat** [comment]
Are you sure `NOSHORTS` was set when you compiled the DLL ?
If `NOSHORTS` is set, we should use `Cint`, otherwise we should use `Cushort`.
In `blockmat.h`

``` c
struct blockrec {
  union blockdatarec data;
  enum blockcat blockcategory;
#ifndef NOSHORTS
  unsigned short blocksize;
#else
  int blocksize;
#endif
};
...
struct sparseblock {
  struct sparseblock *next;
  struct sparseblock *nextbyblock;
  double *entries;
#ifndef NOSHORTS
  unsigned short *iindices;
  unsigned short *jindices;
  int numentries;
  unsigned short blocknum;
  unsigned short blocksize;
  unsigned short constraintnum;
  unsigned short issparse;
#else
  int *iindices;
  int *jindices;
  int numentries;
  int blocknum;
  int blocksize;
  int constraintnum;
  int issparse;
#endif
};
```

**Comment by EQt** [comment]
> Are you sure `NOSHORTS` was set when you compiled the DLL ?

The DLL was cross-compiled, long time ago. You might check the size of the structs by calling

``` julia
CSDP.print_sizeof()
```

**Comment by EQt** [comment]
> And then it stays at `Iter 0`...

Happens the same in Appveyor...
Unfortunately, I don't have time, nor do I have a windows machine available to debug that.

**Comment by blegat** [comment]
I think I have fixed the issue with Windows in #8
I get this: `ccall: could not find function print_sizeof in library`

**Comment by blegat** [comment]
I would really need a function like `print_sizeof`. Do you remember where it was ?

**Comment by EQt** [comment]
I included my own code (`deps/src/debug-mat.c`). So you would have to recompile the DLL to include that code.

**Comment by blegat** [comment]
Closed by https://github.com/JuliaOpt/CSDP.jl/pull/8
