### ISSUE TITLE
Test failures from Convex.jl tests

### ISSUE THREAD

**Issue by ericphanson** [jump-dev/CSDP.jl#55]
See here: https://ericphanson.github.io/ConvexTests.jl/dev/CSDP.html (and see [here](https://discourse.julialang.org/t/ann-convex-0-13-released/35304/2) for a discourse post introducing that repo, ConvexTests.jl). Some of the failures might just be settings and things like that; e.g., with COSMO [most of the failures were max-iteration related](https://github.com/ericphanson/ConvexTests.jl/pull/1), but it would be great to figure out what settings can solve a variety of problems to `1e-3`, and it's possible the tests are surfacing bugs as well.

With the dualization tests it's possible that there are problems coming from Dualization.jl instead of CSDP.jl; I'm not really sure.

**Comment by odow** [comment]
Closing in favor of #74. There are a lot of failing tests in MOI too, and they cover much of the same ground:

https://github.com/jump-dev/CSDP.jl/blob/64266b6d5808b05a7bc15e78de91d59f957295a2/test/MOI_wrapper.jl#L84-L107
