### ISSUE TITLE
Option :write_prob tries to read a nonexistant field m.As

### ISSUE THREAD

**Issue by votroto** [jump-dev/CSDP.jl#58]
The option `:write_prob` does not work.

In `MOI_wrapper.jl`, the first line of `optimize!` is
```
write_prob(optimizer)
```
which tries to access a non-existant field: `m.As` (where `m::Optimizer`) in the file `options.jl`.
```
write_prob(wrtf, m.C, m.b, map(A->A.csdp, m.As))
```
# Small-ish working example:
```
using JuMP
using LinearAlgebra
using CSDP

oo = ()->CSDP.Optimizer(;write_prob="aaa.cspd")
m = Model(oo)

@variable m X[1:2,1:2] Symmetric
A1 = [1 0; 0 1]
C = [2 1; 1 0]
b = [1]
@objective m Min tr(C'*X)
@constraint(m, tr(A1'*X) .== b)
@constraint(m, X in PSDCone())

optimize!(m)
```
which fails with
```
ERROR: type Optimizer has no field As
```

It seems that `m.As` is long gone, the only remaining fields are `b`, `C`, `X`, and their duals; while the `As` are inexplicably inaccessible inside an unmanaged pointer.

Would it be possible to make `As` just as accessible as the other model variables?
If not, would it be possible to make the write-option/export-function work again?
Or is there some other way to get at the `As`?

Thanks! :)

**Comment by blegat** [comment]
We now do not manage these matrices directly and go through an API defined in https://github.com/coin-or/Csdp/pull/12
We should probably add a `write_prob` C function that takes `LoadingProblem` as argument in https://github.com/coin-or/Csdp/pull/12/ and then call it from Julia.
