### ISSUE TITLE
Providing custom CSDP binary

### ISSUE THREAD

**Issue by matbesancon** [jump-dev/CSDP.jl#68]
I didn't find in the deps file how to replace the default CSDP_jll with a custom build

**Comment by matbesancon** [comment]
What is done in many packages is verify the presence of an environment variable providing the location

**Comment by blegat** [comment]
I thought it might be cleaner to just rely on the overriding of artifacts: http://pkgdocs.julialang.org/v1/artifacts/#Overriding-artifact-locations
Never tried it though, it might be good to reference from the README if it works.

**Comment by matbesancon** [comment]
the overriding applies machine-wide, which is slightly different from using an ENV variable right before building on a project-level. This will do for my current case, but might not always be the wanted mechanism

**Comment by blegat** [comment]
From what I understand, you can create an Overwritte.toml in the project folder and it will only apply to the project

**Comment by blegat** [comment]
Closed by https://github.com/jump-dev/JuMP.jl/pull/2823
